дз 1
TuringClubMPEI/AndroidCourse pull request #14
Opened 2023-04-06 15:43 UTC by bsktblman

2023-04-06 19:48 UTC, acediat requested changes

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for (i in 0 until tmp.size - 1)
Не смотря на то, что язык позволяет опускать фигурные скобки в подобных ситуациях - это не очень хорошая практика, так как во многих ситуациях может понизить читаемость кода

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for (i in 0 until tmp.size - 1)
Ну и остальных мест, где фигурные скобки опущены касается

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun sortArr(): IntArray {
Немного странное название, так как у нас и так класс ArrayTools, так зачем здесь еще раз уточнять про массив?

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +class ArrayTools(val x: IntArray = intArrayOf()){
Лучше сделать это поле приватным, так как публичные поля - зло

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +class ArrayTools(val x: IntArray = intArrayOf()){
Ну и имя лучше дать какое-нибудь более говорящее

2023-04-06 19:48 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        var res = x[0];
Тут и в findMax() это имя лучше сменить на более говорящее

2023-04-07 06:38 UTC, VersteckterNebel commented
Ты создал класс и добавил в него поле через конструктор. В методе сортировки ты копируешь значение этого поля в другую переменную и работаешь уже с ней.  Но это несколько противоречит самой концепции ооп. Должно быть так: ты создаешь объект класса с определенным состоянием(в твоем случае это массив)  и при помощи метода сортировки ты должен изменить состояние объекта, то есть изменить его поле - массив. 
Обычно для подобных служебных методов типа поиск минимума, сортировки и т.д создают класс со статическими методами(если пишем на java), в которые передается сам объект, с которым нужно совершить действие. Например в java есть класс Collections и в нем методы типа sort. Можешь, если интересно, посмотреть реализацию. В kotlin же нет статических методов, но вместо этого есть механизм функций-расширений и функций высшего порядка. Поэтому было бы правильнее написать просто глобальную функцию(обычную или расширение) без класса. Но это так, размышления на будущее)

2023-04-07 07:24 UTC, closed without merging