Первое ДЗ
TuringClubMPEI/AndroidCourse pull request #18
Opened 2023-04-08 13:11 UTC by lvsviat

2023-04-08 13:32 UTC, acediat requested changes

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +class Hw1{
Классам надо давать осмысленные названия, в данном случае подошло бы что-то вроде ArrayTools или ArrayUtils

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun min(){ //поиск минимального элемента
Массив стоило бы передать аргументом, а не создавать жестко закрепленный в функции

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun max(){ // поиск максимального элемента
здесь тоже самое про передачу массива аргументом

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        print("Исходный массив: ")
Представление (вывод в консоль) нужно отделять от логики, так что все принтлн-ы лучше вынести в отдельные функции или сделать их в мейне

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for (i in 1..5){
в такой реализации будет работать только с массивом из 5 элементов. Лучше сделать for (i in 1..numbers.size - 1)

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun max(){ // поиск максимального элемента
короче к этой функции все тоже самое, что и к min()

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun sortmax(){ //функция сортировки пузырьком
все тоже самое что и к min()

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for(i in 0..8){
Не уверен, что это так работает, перепроверь пж с разными входными данными

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for(i in 0..8){
сортировка в плане

2023-04-08 13:32 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        var buff :Int
В kotlin принято писать так: var buff: Int

2023-04-08 13:58 UTC, VersteckterNebel commented
Самая главная ошибка в том, что ты решил какой-то набор частных задач. Смысл же задания был в том, чтобы предоставить сортировку для произвольного числового массива.  Если ты решил создать класс, то тебе стоит передавать массив в его конструктор и при помощи методов класса работать уже с этим массивом. Чтобы вывести элементы массива, создай в классе метод, который выводит массив. Помни также про инкапсуляцию: массив должен быть приватным и доступ к нему может осуществляться только через методы класса

2023-04-09 12:49 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    private var test_znach: Int =
Нет особого смысла делать это значение полем

2023-04-09 12:51 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    private var test_znach: Int =
В нейминге переменных в Kotlin используется PascalCase/camelCase, то есть имена классов соответствуют шаблону SomeClassName, а имена полей и методов соответствуют шаблону somePoleName или someMethodName.
К тому же транслит - зло, пишем на инглише

2023-04-09 12:53 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    private val mas: Array<Int> = num
Это поле можно было объявить в конструкторе класса типа:
```kotlin
class ArrayTools(private val mas: Array<Int>) {
```

2023-04-09 12:54 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    private val mas: Array<Int> = num
К тому же имя mas - сокращение от транслита, что не очень хорошо, потому что и сокращения, и транслит - плохой тон

2023-04-09 12:54 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun vivod() {
Транслит

2023-04-09 12:55 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun get_min() {
camelCase

2023-04-09 12:55 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun get_max() {
camelCase

2023-04-09 12:58 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
Перед отправкой сделай ctrl+alt+L. Эта комбинация клавиш отформатирует код в соответствии со стандартом (поставит пробелы где надо, где-то энтеров добавит и тд)

2023-04-11 16:46 UTC, acediat requested changes

2023-04-11 16:46 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun getMin() {
Название с использованием get обычно говорит о том, что эта функция должна возвращать то, что идет после get. В данном случае больше подойдет что-то в стиле outputMin()

2023-04-11 16:46 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        val minimal: Int = min()
Нет смысла создавать здесь отдельную переменную, лучше было бы сделать 
```kotlin
println("Минимальное значение массива: ${min()} ")
```
Возможно даже фигурные скобки не нужны, но мне лень открывать ide чтобы проверить

2023-04-11 16:46 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun getMax() {
тоже самое, что и про getMin()

2023-04-11 16:46 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        var testValue: Int =
Минор: не обязательно уточнять здесь тип

2023-04-13 21:21 UTC, acediat approved these changes

2023-04-13 21:23 UTC, merged