kotov_a_hw1
TuringClubMPEI/AndroidCourse pull request #22
Opened 2023-04-09 16:01 UTC by alexromegrand

2023-04-09 17:23 UTC, VersteckterNebel reviewed
Также в задании нужно было реализовать сортировку. Добавь такой метод в свой класс

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +    val numbers = arrayOf(3, 2, 3, 4, -76, 123, 45, 23, -100)
Задача состояла в том, чтобы написать общий метод сортировки для произвольного числового массива. Поэтому нужно будет переписать класс так, чтобы он принимал в себя массив

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +class Problem(){
Название должно быть связано с решаемой задачей, например ArrayUtils

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +class Problem(){
Пожалуйста, не забывай о правильном форматировании кода. Нажимай в файле всегда ctrl alt l перед отправкой. Intellij Idea добавит пробелы, переносы строк и т.д. То же самое работает и в Android studio

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +        println("Минимальное число = $minpos")
В методе, который отвечает за логику( в нашем случае поиск минимума - часть логики класса), не должно быть никаких операций ввода вывода. Напиши отдельный метод в классе для вывода массива

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun max(){
Здесь то же самое, что в min()

2023-04-09 17:23 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +    val pusk = Problem()
Здесь тоже стоит дать более говорящее название. Попробуй представить,что ты видишь только этот код и не видишь реализации класса Problem. Я думаю, что будет не понятно что такое pusk и Problem. Старайся давать такие названия для сущностей, чтобы было сразу понятно, какую задачу они решают. Я в беседу отправила очень хорошую подробную статью, прочитай ее пожалуйста

2023-04-09 17:27 UTC, VersteckterNebel commented on Homework/hw1/src/main/kotlin/Main.kt
> +        println("Минимальное число = $minpos")
Также методы min и max должны возвращать значения

2023-04-09 18:42 UTC, acediat requested changes

2023-04-09 18:42 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for(i in numbers){
Непонятен смысл этого for-а, минимум можно найти и за один проход по массиву

2023-04-09 18:42 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +        for(i in numbers){
Здесь тоже самое, максимум тоже можно найти за один проход и зачем здесь этот for не очень ясно

2023-04-11 16:40 UTC, acediat requested changes

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun Input_array() {
название функций пишем в camelCase, например: someMethodName

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun Search_max(): Int {
camelCase

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun Sort_array() {
camelCase

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +    fun Output_array() {
camelCase

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +class Arraytools(var size: Int, var base: IntArray = IntArray(size)) {
Ни size, ни base не меняются, так есть ли смысл делать их var? Может лучше сделать их val?

2023-04-11 16:40 UTC, acediat commented on Homework/hw1/src/main/kotlin/Main.kt
> +class Arraytools(var size: Int, var base: IntArray = IntArray(size)) {
А еще лучше сделать их private

2023-04-11 17:18 UTC, acediat approved these changes

2023-04-11 17:21 UTC, merged