hm2
TuringClubMPEI/AndroidCourse pull request #23
Opened 2023-04-10 16:46 UTC by Makrogol

2023-04-10 18:03 UTC, VersteckterNebel requested changes

2023-04-10 18:03 UTC, VersteckterNebel commented on Homework/hw2/src/main/kotlin/Supplier.kt
> +    override fun putFurnitureIntoStorage(storage: Storage, furnitureType: Int, countFurniture: Int): String {
Не нужно также передавать сюда объект склада. этот метод должен только возвращать мебель, которую затребует магазин. Поэтому его нужно переименовать соответствующим образом. 
Создай в интерфейсе магазина метод, который принимает мебель и напиши его реализацию, в которой вызывается соответствующий метод у склада. И передавать мебель в метод магазина нужно будет как раз через метод поставщика

2023-04-10 18:21 UTC, acediat requested changes

2023-04-10 18:21 UTC, acediat commented on Homework/hw2/src/main/kotlin/Shop.kt
> +            return "Bought unsuccessful: isn't so much furniture"
Если используешь строки таким образом, то лучше выносить их в константы где-то за пределом класса типа:
```kotlin
const val BOUGHT_SUCCEFUL = "Bought successful"
```
Это правильнее в силу того, что если тебе потом придется поменять значение это строки, то в текущей реализации тебе придется искать все использования этой строки вручную и в каждом месте её менять, если использовать константу, то ты просто один раз поменяешь константу и все будет хорошо

2023-04-10 18:21 UTC, acediat commented on Homework/hw2/src/main/kotlin/Storage.kt
> +    private var furniture: Array<Int> = arrayOf(0, 0, 0)
Еще тут не обязательно уточнять тип поля

2023-04-10 18:21 UTC, acediat commented on Homework/hw2/src/main/kotlin/Storage.kt
> +            return "Ok"
Константы

2023-04-10 18:21 UTC, acediat commented on Homework/hw2/src/main/kotlin/Supplier.kt
> +            return "Putting Success"
Константы

2023-04-10 18:21 UTC, acediat commented on Homework/hw2/src/main/kotlin/Shop.kt
> +            return "Bought unsuccessful: isn't so much furniture"
А еще лучше использовать enum или sealed class, но мы это пока не проходили, так что если захочется - можешь сам посмотреть как это использовать

2023-04-12 18:01 UTC, VersteckterNebel approved these changes

2023-04-12 18:17 UTC, merged