Домашнее задание №2
TuringClubMPEI/AndroidCourse pull request #24
Opened 2023-04-10 17:14 UTC by bsktblman

2023-04-10 18:58 UTC, acediat requested changes

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Shop.kt
> +        return if (itemToBuy in storage.stockRoom) {
В данном случае можно использовать следующий синтаксис вместо return:
```kotlin
fun buyFurniture(itemToBuy: String) = if(itemToBuy in storage.stockRoom) { // ect...
```

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Shop.kt
> +class Ikea(st: Store) : Shop{
сокращения - зло

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Shop.kt
> +class Ikea(st: Store) : Shop{
К тому же, если перенести из интерфейса все то, что должно быть в реализации, то поле storage можно объявить прямо в конструкторе
```kotlin
class Ikea(private val storage: Store)
```

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Storage.kt
> +    fun delFurniture(itemToDel: String){
Сокращения - зло

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Supplier.kt
>  interface Supplier {
Те же замечания, как и к прошлым интерфейсам

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Supplier.kt
> +class Supplier2(x: List<String>, s: String, t: Storage) : Supplier {
Понимаю, что это учебное задание, но Supplier2 все еще не очень хороший нейминг

2023-04-10 18:58 UTC, acediat commented on Homework/hw2/src/main/kotlin/Supplier.kt
> +class Supplier2(x: List<String>, s: String, t: Storage) : Supplier {
кстати x, s и t тоже стоило бы по-другому назвать

2023-04-10 19:11 UTC, VersteckterNebel commented on Homework/hw2/src/main/kotlin/Storage.kt
> +class Store(st: MutableList<String>) : Storage{
ctrl alt L )

2023-04-13 16:28 UTC, acediat requested changes

2023-04-13 21:19 UTC, acediat approved these changes

2023-04-13 21:19 UTC, merged